export { default as Header } from './Header'
export { default as Footer } from './Footer'
export { default as Home } from './Home'
export { default as OurService } from './OurService'
export { default as WhyUs } from './WhyUs'
export { default as Testimonial } from './Testimonial'
export { default as Rectangle } from './Rectangle'
export { default as Faq } from './Faq'